//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFBS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPETENCIA
    {
        public COMPETENCIA()
        {
            this.EVALUACION = new HashSet<EVALUACION>();
            this.HABILIDAD = new HashSet<HABILIDAD>();
            this.OBSERVACION_COMPETENCIA = new HashSet<OBSERVACION_COMPETENCIA>();
            this.AREA = new HashSet<AREA>();
        }
    
        public decimal ID_COMPETENCIA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public string SIGLA { get; set; }
        public decimal OBSOLETA { get; set; }
        public decimal NIVEL_OPTIMO_ESPERADO { get; set; }
        public string PREGUNTA_ASOCIADA { get; set; }
    
        public virtual ICollection<EVALUACION> EVALUACION { get; set; }
        public virtual ICollection<HABILIDAD> HABILIDAD { get; set; }
        public virtual ICollection<OBSERVACION_COMPETENCIA> OBSERVACION_COMPETENCIA { get; set; }
        public virtual ICollection<AREA> AREA { get; set; }
    }
}
