//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFBS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABILIDAD
    {
        public decimal ID_HABILIDAD { get; set; }
        public Nullable<decimal> ID_COMPETENCIA { get; set; }
        public string NOMBRE { get; set; }
        public decimal ORDEN_ASIGNADO { get; set; }
        public string ALTERNATIVA_PREGUNTA { get; set; }
    
        public virtual COMPETENCIA COMPETENCIA { get; set; }
    }
}
