//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFBS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFIL_DE_CARGO
    {
        public PERFIL_DE_CARGO()
        {
            this.AREA = new HashSet<AREA>();
        }
    
        public decimal ID_PERFIL_DE_CARGO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal OBSOLETO { get; set; }
        public string ID_AREAS { get; set; }
    
        public virtual ICollection<AREA> AREA { get; set; }
    }
}
