//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFBS.Presentation.ServiceWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWCF.IServiceWFBS")]
    public interface IServiceWFBS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/CrearCompetencia", ReplyAction="http://tempuri.org/IServiceWFBS/CrearCompetenciaResponse")]
        bool CrearCompetencia(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/CrearCompetencia", ReplyAction="http://tempuri.org/IServiceWFBS/CrearCompetenciaResponse")]
        System.Threading.Tasks.Task<bool> CrearCompetenciaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/ActualizarCompetencia", ReplyAction="http://tempuri.org/IServiceWFBS/ActualizarCompetenciaResponse")]
        bool ActualizarCompetencia(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/ActualizarCompetencia", ReplyAction="http://tempuri.org/IServiceWFBS/ActualizarCompetenciaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarCompetenciaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/EliminarCompetencia", ReplyAction="http://tempuri.org/IServiceWFBS/EliminarCompetenciaResponse")]
        bool EliminarCompetencia(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/EliminarCompetencia", ReplyAction="http://tempuri.org/IServiceWFBS/EliminarCompetenciaResponse")]
        System.Threading.Tasks.Task<bool> EliminarCompetenciaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerCompetencia", ReplyAction="http://tempuri.org/IServiceWFBS/LeerCompetenciaResponse")]
        string LeerCompetencia(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerCompetencia", ReplyAction="http://tempuri.org/IServiceWFBS/LeerCompetenciaResponse")]
        System.Threading.Tasks.Task<string> LeerCompetenciaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerCompetencias", ReplyAction="http://tempuri.org/IServiceWFBS/LeerCompetenciasResponse")]
        string LeerCompetencias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerCompetencias", ReplyAction="http://tempuri.org/IServiceWFBS/LeerCompetenciasResponse")]
        System.Threading.Tasks.Task<string> LeerCompetenciasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/CrearHabilidad", ReplyAction="http://tempuri.org/IServiceWFBS/CrearHabilidadResponse")]
        bool CrearHabilidad(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/CrearHabilidad", ReplyAction="http://tempuri.org/IServiceWFBS/CrearHabilidadResponse")]
        System.Threading.Tasks.Task<bool> CrearHabilidadAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/ActualizarHabilidad", ReplyAction="http://tempuri.org/IServiceWFBS/ActualizarHabilidadResponse")]
        bool ActualizarHabilidad(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/ActualizarHabilidad", ReplyAction="http://tempuri.org/IServiceWFBS/ActualizarHabilidadResponse")]
        System.Threading.Tasks.Task<bool> ActualizarHabilidadAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/EliminarHabilidad", ReplyAction="http://tempuri.org/IServiceWFBS/EliminarHabilidadResponse")]
        bool EliminarHabilidad(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/EliminarHabilidad", ReplyAction="http://tempuri.org/IServiceWFBS/EliminarHabilidadResponse")]
        System.Threading.Tasks.Task<bool> EliminarHabilidadAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerHabilidad", ReplyAction="http://tempuri.org/IServiceWFBS/LeerHabilidadResponse")]
        string LeerHabilidad(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerHabilidad", ReplyAction="http://tempuri.org/IServiceWFBS/LeerHabilidadResponse")]
        System.Threading.Tasks.Task<string> LeerHabilidadAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerHabilidades", ReplyAction="http://tempuri.org/IServiceWFBS/LeerHabilidadesResponse")]
        string LeerHabilidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerHabilidades", ReplyAction="http://tempuri.org/IServiceWFBS/LeerHabilidadesResponse")]
        System.Threading.Tasks.Task<string> LeerHabilidadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerHabPorCom", ReplyAction="http://tempuri.org/IServiceWFBS/LeerHabPorComResponse")]
        string LeerHabPorCom(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerHabPorCom", ReplyAction="http://tempuri.org/IServiceWFBS/LeerHabPorComResponse")]
        System.Threading.Tasks.Task<string> LeerHabPorComAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/CrearPeriodoEvaluacion", ReplyAction="http://tempuri.org/IServiceWFBS/CrearPeriodoEvaluacionResponse")]
        bool CrearPeriodoEvaluacion(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/CrearPeriodoEvaluacion", ReplyAction="http://tempuri.org/IServiceWFBS/CrearPeriodoEvaluacionResponse")]
        System.Threading.Tasks.Task<bool> CrearPeriodoEvaluacionAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/ActualizarPeriodoEvaluacion", ReplyAction="http://tempuri.org/IServiceWFBS/ActualizarPeriodoEvaluacionResponse")]
        bool ActualizarPeriodoEvaluacion(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/ActualizarPeriodoEvaluacion", ReplyAction="http://tempuri.org/IServiceWFBS/ActualizarPeriodoEvaluacionResponse")]
        System.Threading.Tasks.Task<bool> ActualizarPeriodoEvaluacionAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/EliminarPeriodoEvaluacion", ReplyAction="http://tempuri.org/IServiceWFBS/EliminarPeriodoEvaluacionResponse")]
        bool EliminarPeriodoEvaluacion(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/EliminarPeriodoEvaluacion", ReplyAction="http://tempuri.org/IServiceWFBS/EliminarPeriodoEvaluacionResponse")]
        System.Threading.Tasks.Task<bool> EliminarPeriodoEvaluacionAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerPeriodoEvaluacion", ReplyAction="http://tempuri.org/IServiceWFBS/LeerPeriodoEvaluacionResponse")]
        string LeerPeriodoEvaluacion(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerPeriodoEvaluacion", ReplyAction="http://tempuri.org/IServiceWFBS/LeerPeriodoEvaluacionResponse")]
        System.Threading.Tasks.Task<string> LeerPeriodoEvaluacionAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerPeriodosEvaluaciones", ReplyAction="http://tempuri.org/IServiceWFBS/LeerPeriodosEvaluacionesResponse")]
        string LeerPeriodosEvaluaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerPeriodosEvaluaciones", ReplyAction="http://tempuri.org/IServiceWFBS/LeerPeriodosEvaluacionesResponse")]
        System.Threading.Tasks.Task<string> LeerPeriodosEvaluacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/ValidarUsuario", ReplyAction="http://tempuri.org/IServiceWFBS/ValidarUsuarioResponse")]
        bool ValidarUsuario(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/ValidarUsuario", ReplyAction="http://tempuri.org/IServiceWFBS/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/Desactivado", ReplyAction="http://tempuri.org/IServiceWFBS/DesactivadoResponse")]
        bool Desactivado(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/Desactivado", ReplyAction="http://tempuri.org/IServiceWFBS/DesactivadoResponse")]
        System.Threading.Tasks.Task<bool> DesactivadoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/CrearUsuario", ReplyAction="http://tempuri.org/IServiceWFBS/CrearUsuarioResponse")]
        bool CrearUsuario(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/CrearUsuario", ReplyAction="http://tempuri.org/IServiceWFBS/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<bool> CrearUsuarioAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/ActualizarUsuario", ReplyAction="http://tempuri.org/IServiceWFBS/ActualizarUsuarioResponse")]
        bool ActualizarUsuario(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/ActualizarUsuario", ReplyAction="http://tempuri.org/IServiceWFBS/ActualizarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ActualizarUsuarioAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/EliminarUsuario", ReplyAction="http://tempuri.org/IServiceWFBS/EliminarUsuarioResponse")]
        bool EliminarUsuario(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/EliminarUsuario", ReplyAction="http://tempuri.org/IServiceWFBS/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerUsuario", ReplyAction="http://tempuri.org/IServiceWFBS/LeerUsuarioResponse")]
        string LeerUsuario(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerUsuario", ReplyAction="http://tempuri.org/IServiceWFBS/LeerUsuarioResponse")]
        System.Threading.Tasks.Task<string> LeerUsuarioAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerUsuarios", ReplyAction="http://tempuri.org/IServiceWFBS/LeerUsuariosResponse")]
        string LeerUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerUsuarios", ReplyAction="http://tempuri.org/IServiceWFBS/LeerUsuariosResponse")]
        System.Threading.Tasks.Task<string> LeerUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/CrearArea", ReplyAction="http://tempuri.org/IServiceWFBS/CrearAreaResponse")]
        bool CrearArea(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/CrearArea", ReplyAction="http://tempuri.org/IServiceWFBS/CrearAreaResponse")]
        System.Threading.Tasks.Task<bool> CrearAreaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/ActualizarArea", ReplyAction="http://tempuri.org/IServiceWFBS/ActualizarAreaResponse")]
        bool ActualizarArea(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/ActualizarArea", ReplyAction="http://tempuri.org/IServiceWFBS/ActualizarAreaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarAreaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/EliminarArea", ReplyAction="http://tempuri.org/IServiceWFBS/EliminarAreaResponse")]
        bool EliminarArea(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/EliminarArea", ReplyAction="http://tempuri.org/IServiceWFBS/EliminarAreaResponse")]
        System.Threading.Tasks.Task<bool> EliminarAreaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerArea", ReplyAction="http://tempuri.org/IServiceWFBS/LeerAreaResponse")]
        string LeerArea(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerArea", ReplyAction="http://tempuri.org/IServiceWFBS/LeerAreaResponse")]
        System.Threading.Tasks.Task<string> LeerAreaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerAreas", ReplyAction="http://tempuri.org/IServiceWFBS/LeerAreasResponse")]
        string LeerAreas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerAreas", ReplyAction="http://tempuri.org/IServiceWFBS/LeerAreasResponse")]
        System.Threading.Tasks.Task<string> LeerAreasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/CrearPerfildeCargo", ReplyAction="http://tempuri.org/IServiceWFBS/CrearPerfildeCargoResponse")]
        bool CrearPerfildeCargo(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/CrearPerfildeCargo", ReplyAction="http://tempuri.org/IServiceWFBS/CrearPerfildeCargoResponse")]
        System.Threading.Tasks.Task<bool> CrearPerfildeCargoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/ActualizarPerfildeCargo", ReplyAction="http://tempuri.org/IServiceWFBS/ActualizarPerfildeCargoResponse")]
        bool ActualizarPerfildeCargo(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/ActualizarPerfildeCargo", ReplyAction="http://tempuri.org/IServiceWFBS/ActualizarPerfildeCargoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarPerfildeCargoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/EliminarPerfildeCargo", ReplyAction="http://tempuri.org/IServiceWFBS/EliminarPerfildeCargoResponse")]
        bool EliminarPerfildeCargo(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/EliminarPerfildeCargo", ReplyAction="http://tempuri.org/IServiceWFBS/EliminarPerfildeCargoResponse")]
        System.Threading.Tasks.Task<bool> EliminarPerfildeCargoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerPerfildeCargo", ReplyAction="http://tempuri.org/IServiceWFBS/LeerPerfildeCargoResponse")]
        string LeerPerfildeCargo(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerPerfildeCargo", ReplyAction="http://tempuri.org/IServiceWFBS/LeerPerfildeCargoResponse")]
        System.Threading.Tasks.Task<string> LeerPerfildeCargoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerPerfilesdeCargo", ReplyAction="http://tempuri.org/IServiceWFBS/LeerPerfilesdeCargoResponse")]
        string LeerPerfilesdeCargo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWFBS/LeerPerfilesdeCargo", ReplyAction="http://tempuri.org/IServiceWFBS/LeerPerfilesdeCargoResponse")]
        System.Threading.Tasks.Task<string> LeerPerfilesdeCargoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWFBSChannel : WFBS.Presentation.ServiceWCF.IServiceWFBS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWFBSClient : System.ServiceModel.ClientBase<WFBS.Presentation.ServiceWCF.IServiceWFBS>, WFBS.Presentation.ServiceWCF.IServiceWFBS {
        
        public ServiceWFBSClient() {
        }
        
        public ServiceWFBSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWFBSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWFBSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWFBSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CrearCompetencia(string xml) {
            return base.Channel.CrearCompetencia(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearCompetenciaAsync(string xml) {
            return base.Channel.CrearCompetenciaAsync(xml);
        }
        
        public bool ActualizarCompetencia(string xml) {
            return base.Channel.ActualizarCompetencia(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarCompetenciaAsync(string xml) {
            return base.Channel.ActualizarCompetenciaAsync(xml);
        }
        
        public bool EliminarCompetencia(string xml) {
            return base.Channel.EliminarCompetencia(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarCompetenciaAsync(string xml) {
            return base.Channel.EliminarCompetenciaAsync(xml);
        }
        
        public string LeerCompetencia(string xml) {
            return base.Channel.LeerCompetencia(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerCompetenciaAsync(string xml) {
            return base.Channel.LeerCompetenciaAsync(xml);
        }
        
        public string LeerCompetencias() {
            return base.Channel.LeerCompetencias();
        }
        
        public System.Threading.Tasks.Task<string> LeerCompetenciasAsync() {
            return base.Channel.LeerCompetenciasAsync();
        }
        
        public bool CrearHabilidad(string xml) {
            return base.Channel.CrearHabilidad(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearHabilidadAsync(string xml) {
            return base.Channel.CrearHabilidadAsync(xml);
        }
        
        public bool ActualizarHabilidad(string xml) {
            return base.Channel.ActualizarHabilidad(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarHabilidadAsync(string xml) {
            return base.Channel.ActualizarHabilidadAsync(xml);
        }
        
        public bool EliminarHabilidad(string xml) {
            return base.Channel.EliminarHabilidad(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarHabilidadAsync(string xml) {
            return base.Channel.EliminarHabilidadAsync(xml);
        }
        
        public string LeerHabilidad(string xml) {
            return base.Channel.LeerHabilidad(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerHabilidadAsync(string xml) {
            return base.Channel.LeerHabilidadAsync(xml);
        }
        
        public string LeerHabilidades() {
            return base.Channel.LeerHabilidades();
        }
        
        public System.Threading.Tasks.Task<string> LeerHabilidadesAsync() {
            return base.Channel.LeerHabilidadesAsync();
        }
        
        public string LeerHabPorCom(int id) {
            return base.Channel.LeerHabPorCom(id);
        }
        
        public System.Threading.Tasks.Task<string> LeerHabPorComAsync(int id) {
            return base.Channel.LeerHabPorComAsync(id);
        }
        
        public bool CrearPeriodoEvaluacion(string xml) {
            return base.Channel.CrearPeriodoEvaluacion(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearPeriodoEvaluacionAsync(string xml) {
            return base.Channel.CrearPeriodoEvaluacionAsync(xml);
        }
        
        public bool ActualizarPeriodoEvaluacion(string xml) {
            return base.Channel.ActualizarPeriodoEvaluacion(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarPeriodoEvaluacionAsync(string xml) {
            return base.Channel.ActualizarPeriodoEvaluacionAsync(xml);
        }
        
        public bool EliminarPeriodoEvaluacion(string xml) {
            return base.Channel.EliminarPeriodoEvaluacion(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarPeriodoEvaluacionAsync(string xml) {
            return base.Channel.EliminarPeriodoEvaluacionAsync(xml);
        }
        
        public string LeerPeriodoEvaluacion(string xml) {
            return base.Channel.LeerPeriodoEvaluacion(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerPeriodoEvaluacionAsync(string xml) {
            return base.Channel.LeerPeriodoEvaluacionAsync(xml);
        }
        
        public string LeerPeriodosEvaluaciones() {
            return base.Channel.LeerPeriodosEvaluaciones();
        }
        
        public System.Threading.Tasks.Task<string> LeerPeriodosEvaluacionesAsync() {
            return base.Channel.LeerPeriodosEvaluacionesAsync();
        }
        
        public bool ValidarUsuario(string xml) {
            return base.Channel.ValidarUsuario(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string xml) {
            return base.Channel.ValidarUsuarioAsync(xml);
        }
        
        public bool Desactivado(string xml) {
            return base.Channel.Desactivado(xml);
        }
        
        public System.Threading.Tasks.Task<bool> DesactivadoAsync(string xml) {
            return base.Channel.DesactivadoAsync(xml);
        }
        
        public bool CrearUsuario(string xml) {
            return base.Channel.CrearUsuario(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearUsuarioAsync(string xml) {
            return base.Channel.CrearUsuarioAsync(xml);
        }
        
        public bool ActualizarUsuario(string xml) {
            return base.Channel.ActualizarUsuario(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarUsuarioAsync(string xml) {
            return base.Channel.ActualizarUsuarioAsync(xml);
        }
        
        public bool EliminarUsuario(string xml) {
            return base.Channel.EliminarUsuario(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(string xml) {
            return base.Channel.EliminarUsuarioAsync(xml);
        }
        
        public string LeerUsuario(string xml) {
            return base.Channel.LeerUsuario(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerUsuarioAsync(string xml) {
            return base.Channel.LeerUsuarioAsync(xml);
        }
        
        public string LeerUsuarios() {
            return base.Channel.LeerUsuarios();
        }
        
        public System.Threading.Tasks.Task<string> LeerUsuariosAsync() {
            return base.Channel.LeerUsuariosAsync();
        }
        
        public bool CrearArea(string xml) {
            return base.Channel.CrearArea(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearAreaAsync(string xml) {
            return base.Channel.CrearAreaAsync(xml);
        }
        
        public bool ActualizarArea(string xml) {
            return base.Channel.ActualizarArea(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarAreaAsync(string xml) {
            return base.Channel.ActualizarAreaAsync(xml);
        }
        
        public bool EliminarArea(string xml) {
            return base.Channel.EliminarArea(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAreaAsync(string xml) {
            return base.Channel.EliminarAreaAsync(xml);
        }
        
        public string LeerArea(string xml) {
            return base.Channel.LeerArea(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerAreaAsync(string xml) {
            return base.Channel.LeerAreaAsync(xml);
        }
        
        public string LeerAreas() {
            return base.Channel.LeerAreas();
        }
        
        public System.Threading.Tasks.Task<string> LeerAreasAsync() {
            return base.Channel.LeerAreasAsync();
        }
        
        public bool CrearPerfildeCargo(string xml) {
            return base.Channel.CrearPerfildeCargo(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearPerfildeCargoAsync(string xml) {
            return base.Channel.CrearPerfildeCargoAsync(xml);
        }
        
        public bool ActualizarPerfildeCargo(string xml) {
            return base.Channel.ActualizarPerfildeCargo(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarPerfildeCargoAsync(string xml) {
            return base.Channel.ActualizarPerfildeCargoAsync(xml);
        }
        
        public bool EliminarPerfildeCargo(string xml) {
            return base.Channel.EliminarPerfildeCargo(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarPerfildeCargoAsync(string xml) {
            return base.Channel.EliminarPerfildeCargoAsync(xml);
        }
        
        public string LeerPerfildeCargo(string xml) {
            return base.Channel.LeerPerfildeCargo(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerPerfildeCargoAsync(string xml) {
            return base.Channel.LeerPerfildeCargoAsync(xml);
        }
        
        public string LeerPerfilesdeCargo() {
            return base.Channel.LeerPerfilesdeCargo();
        }
        
        public System.Threading.Tasks.Task<string> LeerPerfilesdeCargoAsync() {
            return base.Channel.LeerPerfilesdeCargoAsync();
        }
    }
}
